site_name: Raspberry Pi Setup Guide
repo_url: https://github.com/tom-davies/pi-guide
nav:
  - Guide:
    - 'Device Setup': setup.md
    - 'Security': security.md
    - 'Docker Containers': docker.md
    #- 'Cloudflare & DNS': dns.md
  - Other Resources: resources.md
theme:
  name: material
  palette:
    scheme: slate
    primary: pink
    accent: purple
